export const header: string;
export const logo: string;
export const trigger: string;
export const right: string;
export const sider: string;
export const action: string;
export const search: string;
export const account: string;
export const avatar: string;
